<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="Emails\Resources\EmailSubjects.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>EmailSubjects.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <None Remove="Emails\Resources\Templates\**\*.html" />
      <EmbeddedResource Include="Emails\Resources\Templates\**\*.html" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Emails\Resources\EmailSubjects.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>EmailSubjects.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.6" />
      <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="9.0.6" />
      <PackageReference Include="RazorEngine.NetCore" Version="3.1.1" />
    </ItemGroup>
</Project>
